### ISSUE TITLE
SCEUA set parameter

### ISSUE THREAD

**Issue by dingxinjun** [thouska/spotpy#297]
spotpy.parameter.Uniform are generate param uniformly between lower and upper bound. how can i set the  uniform to log uniform between log(-10) to log(10).

**Comment by thouska** [comment]
Hi @dingxinjun,
thank you for your message. A log-uniform function is not yet part of the implemented parameter distributions in sptopy. But I guess it shouldn't be too hard to implement. One could build up e.g. on the implemented [lognormal](https://github.com/thouska/spotpy/blob/master/src/spotpy/parameter.py#L399) function and adjust it to be loguniform. @dingxinjun do you think you could provide a pull-request that works for your needs? I would be happy to merge and provide it with the next spotpy version.

**Comment by dingxinjun** [comment]
class Uniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """
    __rndargs__ = 'low', 'high'
    def __init__(self, *args, **kwargs):
        """
        :name: Name of the parameter
        :low: lower bound of the uniform distribution
        :high: higher bound of the uniform distribution
        :step:     (optional) number for step size required for some algorithms, 
                eg. mcmc need a parameter of the variance for the next step
                default is median of rndfunc(*rndargs, size=1000)
        :optguess: (optional) number for start point of parameter
                default is quantile(0.5) - quantile(0.4) of 
                rndfunc(*rndargs, size=1000) 
        """
        super(Uniform, self).__init__(rnd.uniform, 'Uniform', *args, **kwargs)

class loguniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """
    __rndargs__ = 'low', 'high'
    def __init__(self, *args, **kwargs):
        """
        :name: Name of the parameter
        :low: lower bound of the uniform distribution
        :high: higher bound of the uniform distribution
        :step:     (optional) number for step size required for some algorithms,
                eg. mcmc need a parameter of the variance for the next step
                default is median of rndfunc(*rndargs, size=1000)
        :optguess: (optional) number for start point of parameter
                default is quantile(0.5) - quantile(0.4) of
                rndfunc(*rndargs, size=1000)
        """
        super(loguniform, self).__init__(rnd.uniform, 'loguniform', *args, **kwargs)


I only copy the uniform class,but i'm not sure the code is right or not

**Comment by thouska** [comment]
I guess we would need to work with:

> from scipy.stats import loguniform

and implement it accordingly in this super(..).init(...), right? 
The [example](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.loguniform.html) looks like it's similar use to the implemented numpy.random stuff.

**Comment by dingxinjun** [comment]
class Uniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """
    __rndargs__ = 'low', 'high'
    def __init__(self, *args, **kwargs):
        """
        :name: Name of the parameter
        :low: lower bound of the uniform distribution
        :high: higher bound of the uniform distribution
        :step:     (optional) number for step size required for some algorithms, 
                eg. mcmc need a parameter of the variance for the next step
                default is median of rndfunc(*rndargs, size=1000)
        :optguess: (optional) number for start point of parameter
                default is quantile(0.5) - quantile(0.4) of 
                rndfunc(*rndargs, size=1000) 
        """
        super(Uniform, self).__init__(rnd.uniform, 'Uniform', *args, **kwargs)

class loguniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """
    __rndargs__ = 'low', 'high'
    def __init__(self, *args, **kwargs):
        """
        :name: Name of the parameter
        :low: lower bound of the uniform distribution
        :high: higher bound of the uniform distribution
        :step:     (optional) number for step size required for some algorithms,
                eg. mcmc need a parameter of the variance for the next step
                default is median of rndfunc(*rndargs, size=1000)
        :optguess: (optional) number for start point of parameter
                default is quantile(0.5) - quantile(0.4) of
                rndfunc(*rndargs, size=1000)
        """
        super(loguniform, self).__init__(loguniform, 'loguniform', *args, **kwargs)

i just follow the uniform class but it does not work, Can you give me a pre-release version of log uniform

**Comment by thouska** [comment]
No worries, I implemented a branch with has a pre-release version, but haven't tested it. Would you like to have a look?
https://github.com/thouska/spotpy/blob/Lognormal-implementation/src/spotpy/parameter.py#L294

**Comment by thouska** [comment]
Oh, yes seems like the scipy loguniform function comes with [different methods](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.loguniform.html#scipy.stats.loguniform). I implemented the rvs (random vairates) method and updated the code linked above. That should work now. But is it, what you need?

**Comment by dingxinjun** [comment]
Traceback (most recent call last):
  File "C:\D\software\anaconda\anaconda_install\envs\hydrogr2\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-585ac0dc3f7a>", line 1, in <cell line: 1>
    runfile('C:/E/GR2M_project/GR2M_SNOW_CODE - v1.1 - no_warmup/main_debug_camel.py', wdir='C:/E/GR2M_project/GR2M_SNOW_CODE - v1.1 - no_warmup')
  File "C:\D\software\anaconda\pycharm_install\PyCharm 2022.1.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\D\software\anaconda\pycharm_install\PyCharm 2022.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/E/GR2M_project/GR2M_SNOW_CODE - v1.1 - no_warmup/main_debug_camel.py", line 91, in <module>
    basin.calibration('1957-01-01', '1972-12-01', spin_up_date='1960-01-01')
  File "C:\E\GR2M_project\GR2M_SNOW_CODE - v1.1 - no_warmup\gr2m.py", line 127, in calibration
    params=calibrate.calibrate(self.calibrate_precipitation, self.calibrate_evaporation,self.calibrate_Temp_avg,
  File "C:\E\GR2M_project\GR2M_SNOW_CODE - v1.1 - no_warmup\calibrate.py", line 133, in calibrate
    sampler = spotpy.algorithms.sceua(spotpy_setup(precipitation, evaporation,average_temperature, discharge, initial_state, init_params),
  File "C:\E\GR2M_project\GR2M_SNOW_CODE - v1.1 - no_warmup\calibrate.py", line 38, in __init__
    spotpy.parameter.Loguniform('W0', 0, 1, optguess=init_params['W0']),
  File "C:\D\software\anaconda\anaconda_install\envs\hydrogr2\lib\site-packages\spotpy\parameter.py", line 303, in __init__
    super(Loguniform, self).__init__(loguniform.rvs, "Loguniform", *args, **kwargs)
  File "C:\D\software\anaconda\anaconda_install\envs\hydrogr2\lib\site-packages\spotpy\parameter.py", line 195, in __init__
    sample = self(size=1000)
  File "C:\D\software\anaconda\anaconda_install\envs\hydrogr2\lib\site-packages\spotpy\parameter.py", line 220, in __call__
    return self.rndfunc(*self.rndargs, **kwargs)
  File "C:\D\software\anaconda\anaconda_install\envs\hydrogr2\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1067, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.


i copy the whole parameter.py file but lognormal  raise error

**Comment by dingxinjun** [comment]
it work now a param low boundary i set to 0 ,i change 0 to 0000000001,it works

**Comment by dingxinjun** [comment]
thanks, very much, Dear thouska will you code a new program like dataassimilation?
