### ISSUE TITLE
MPI Error

### ISSUE THREAD

**Issue by theobarnhart** [thouska/spotpy#32]
Dear SpotPy Team,

First, thank you for creating this package, it is just what I was looking for.

I'm working to get a parallel SCE-AU optimization running with a hydrologic model I'm using; however, when I test the MPI functionality on my machine with the Ackley function I get an error. 

`$ mpirun -c 3 optimizer_experiment.py`
`--------------------------------------------------------------------------`
`mpirun noticed that the job aborted, but has no info as to the process`
`that caused that situation.`
`--------------------------------------------------------------------------`

When I run just the script I get the following error:

`$ python optimizer_experiment.py`
`Traceback (most recent call last):`
`  File "optimizer_experiment.py", line 46, in <module>
    sampler=spotpy.algorithms.sceua(spotpy_setup,dbname='ackleySCEUA',dbformat='csv', parallel='mpi')`
  `File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/spotpy/algorithms/sceua.py", line 72, in __init__`
   ` super(sceua, self).__init__(*args, **kwargs)`
  `File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/spotpy/algorithms/_algorithm.py", line 131, in __init__`
`    self.repeat = ForEach(self.simulate)`
`  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/spotpy/parallel/mpi.py", line 44, in __init__`
`    raise RuntimeError('Need at least two processes for parallelization')
RuntimeError: Need at least two processes for parallelization`

If I remove the `parallel='mpi'` from my sample object creation the script runs correctly (I think). 

`$ python optimizer_experiment.py`
`5490 of 100000 (best like=-13.0303)`
`9150 of 100000 (best like=-7.94116)`
`12810 of 100000 (best like=-3.79716)`
`16470 of 100000 (best like=-2.31983)`
`20130 of 100000 (best like=-0.674121)`
`23790 of 100000 (best like=-0.201386)`
`27450 of 100000 (best like=-0.0637782)`
`31110 of 100000 (best like=-0.0189631)`
`34770 of 100000 (best like=-0.00718137)`
`38430 of 100000 (best like=-0.00231183)`
`THE POPULATION HAS CONVERGED TO A PRESPECIFIED SMALL PARAMETER SPACE`
`SEARCH WAS STOPPED AT TRIAL NUMBER: 40260`
`NORMALIZED GEOMETRIC RANGE = 0.000917`
`THE BEST POINT HAS IMPROVED IN LAST 1000 LOOPS BY 100000.000000`
`Best parameter set`
`[ -5.17971160e-04  -2.73393711e-04  -1.59531840e-04  -3.73699424e-04`
 ` -3.83033792e-04   1.28569736e-04  -3.38711833e-05  -4.35466572e-04`
 ` -2.52406601e-04   2.63524254e-04  -2.57554574e-04  -2.25413748e-04`
 ` -9.39373664e-05  -2.64491644e-04  -4.77954988e-05  -5.38896782e-05`
 ` -4.73667061e-05  -2.71087384e-04  -2.91092724e-04  -5.01840057e-04`
 ` -5.98583368e-04   3.66735275e-04  -2.94254801e-04   2.03436106e-04`
  ` 2.25145075e-04  -1.21849923e-04  -6.86020051e-04   6.97691791e-04`
  ` 2.14271000e-04   1.83873481e-04]`
`Duration:25.16 s`

Am I missing something with regard to using MPI to run on multiple cores? I get the same set of errors when I set up spotpy to work around the hydrologic model I'm using ([RHESSys](https://github.com/RHESSys/RHESSys)).

Thank you for your help!

Theo

[optimizer_experiment.txt](https://github.com/thouska/spotpy/files/856657/optimizer_experiment.txt)

**Comment by theobarnhart** [comment]
Hi Tobias,

Thanks for the quick response. I'm working on OS X 10.11.6 (unix under the hood) and I think the problem was with how I configured my setup script. For others who run into this issue, here is what I did:

First, test that mpi is working properly:
`$ mpirun -c 4 demo/helloworldparallel.py`
`Hello, World! I am process 1 of 4 on *****************.`
`Hello, World! I am process 0 of 4 on *****************.`
`Hello, World! I am process 3 of 4 on *****************.`
`Hello, World! I am process 2 of 4 on *****************`

Then add a shebang to the setup script so MPI knows what interpreter to use. I used `#!/Users/barnhatb/anaconda/bin/python`
I usually work in Jupyter notebooks so I often forget to have a shebang...

Then make your setup file executable using `chmod +x test_optimizer_par.py`

Then run the file using: `mpirun -c 3 test_optimizer_par.py`

Since the model I'm using needs to create an folder for each instance thats running at a time I was able to verify that it created 2 separate output folders. For some reason mpirun executes n-1 processed when n is the number of cores I allocate to it on my machine. I'm still working on understanding why that is.
