### ISSUE TITLE
Rosenbrock tutorial throws IndexError

### ISSUE THREAD

**Issue by cpwnd** [thouska/spotpy#33]
Getting an index error when executing the scripts of the Rosenbrock tutorial.
The problem occurs with python 2.7 and 3.5, logs are identical except the python version in path.

Maybe this isn't just a problem only of the rosenbrock example.

### Reproduce

Following the tutorial I typed this into my terminal.
```
$ python spot_setup_rosenbrock.py
$ python tutorial_rosenbrock.py
```

### Error logs
```
End of sampling
4454 of 5000 (best like=-0.0888043)
Best parameter set
[ 1.0977653   1.17693794]
Duration:0.44 s
Creating LatinHyperCube Matrix
Start sampling
End of sampling
1733 of 5000 (best like=-0.0327559)
Best parameter set
[ 0.98364727  0.98558652]
Duration:0.33 s
burnIn...
Beginn Random Walk
End of sampling
Acceptance rate = 0.002
2173 of 5000 (best like=-0.0580164)
Best parameter set:
[ 1.13771839  1.31416423]
Duration:0.4 s
Inititalize  1  chain(s)...
Beginn of Random Walk
End of sampling
1777 of 5000 (best like=-0.920603)
Best parameter set
[ 1.07365684  1.15459551]
Duration:0.53 s
THE POPULATION HAS CONVERGED TO A PRESPECIFIED SMALL PARAMETER SPACE
SEARCH WAS STOPPED AT TRIAL NUMBER: 880
NORMALIZED GEOMETRIC RANGE = 0.000000
THE BEST POINT HAS IMPROVED IN LAST 100 LOOPS BY 100000.000000
Best parameter set
[ 1.  1.]
Duration:0.19 s
5000 of 5000 (best like=-0.00975337)
Duration:0.44 s

/usr/local/lib/python3.5/dist-packages/spotpy-1.2.36-py3.5.egg/spotpy/algorithms/demcz.py:407: RuntimeWarning: overflow encountered in exp
/usr/local/lib/python3.5/dist-packages/spotpy-1.2.36-py3.5.egg/spotpy/algorithms/demcz.py:694: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.5/dist-packages/spotpy-1.2.36-py3.5.egg/spotpy/algorithms/demcz.py:694: RuntimeWarning: invalid value encountered in sqrt
/usr/local/lib/python3.5/dist-packages/spotpy-1.2.36-py3.5.egg/spotpy/algorithms/demcz.py:697: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.5/dist-packages/spotpy-1.2.36-py3.5.egg/spotpy/algorithms/demcz.py:697: RuntimeWarning: invalid value encountered in sqrt

1027 of 1250
Gelman Rubin R=[ 1.07797019  1.08153806]
End of sampling
2 of 1250 (best like=-0.918976)
Best parameter set
[0.98029331058031832, 0.95878236063625377]
Duration:2.75 s
100 input vectors with 2 parameters
Generating 1000 parameters:
Traceback (most recent call last):
  File "tutorial_rosenbrock.py", line 49, in <module>
    sampler.sample(rep)
  File "build/bdist.linux-x86_64/egg/spotpy/algorithms/rope.py", line 134, in sample
  File "build/bdist.linux-x86_64/egg/spotpy/algorithms/rope.py", line 213, in programm_depth
  File "build/bdist.linux-x86_64/egg/spotpy/algorithms/rope.py", line 225, in fHDEPTHAB
  File "build/bdist.linux-x86_64/egg/spotpy/algorithms/rope.py", line 258, in fDEP
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

EDIT: Added the error traceback

**Comment by bees4ever** [comment]
I fixed an int/float error. See here https://github.com/thouska/spotpy/pull/35

**Comment by thouska** [comment]
perfect, your code fixed this error. Thanks @bees4ever !
